### ISSUE TITLE
How is the performance compared to L2-normalization?

### ISSUE THREAD

**Issue by linzhiqiu** [fengyuli2002/distribution-normalization#3]
When extracting the CLIP features, you set "normalize=False". 

I am curious about this ablation:

1. L2-normalized feature
2. L2-normalized feature + your distribution normalization

**Comment by YifeiZhou02** [comment]
Hi,

Thanks for the comment. In our original paper, L2-normalized is already implicitly included in the baseline CLIP. Happy to answer any further question.
